# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.FileField(upload_to='imagenes')),
                ('ruta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.TextField()),
                ('cuerpo', models.TextField(default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('descripcion', models.TextField(default='')),
                ('estado', models.BooleanField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imagen',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Publicacion'),
        ),
    ]
