# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20170815_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cuerpo', models.TextField(blank=True, default='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Publicacion')),
            ],
        ),
    ]
