# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='link',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
